name: HealthTripAway_Submit

on:
#   watch:
#     type: started

  schedule:
    - cron: '40 22 * * *'
    - cron: '20 9 * * *'

jobs:
  submit:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Submit
      run: |
        java -jar HealthTripAway.jar ${{ secrets.USERNAME }} ${{ secrets.FROMMAIL }} ${{ secrets.FROMMAILPW }} ${{ secrets.TOMAIL }} ${{ secrets.SIGNNAME }}
